# Generated by Django 6.0.1 on 2026-02-06 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_priority_complaintupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='location',
            field=models.CharField(blank=True, help_text='Area / Ward / Locality', max_length=100),
        ),
        migrations.AlterField(
            model_name='complaintupdate',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='complaints.complaint'),
        ),
        migrations.AlterField(
            model_name='complaintupdate',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], max_length=20),
        ),
    ]
