# Generated by Django 6.0.1 on 2026-02-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_location_alter_complaintupdate_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sla_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
