# Generated by Django 6.0.1 on 2026-02-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaint_is_overdue_complaint_sla_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='other_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
