# Generated by Django 6.0.1 on 2026-02-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_other_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintupdate',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_updates/'),
        ),
    ]
